apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: go-simple-webserver
  labels:
    app: go-simple-webserver
spec:
  replicas: 10
  strategy:
    canary:
      steps:
        - setWeight: 50
        - pause: { duration: 60s }
        - setWeight: 100
  selector:
    matchLabels:
      app: go-simple-webserver
  template:
    metadata:
      labels:
        app: go-simple-webserver
    spec:
      containers:
        - name: webserver
          image: ghcr.io/bogdanpaul15/ci_cd_lab@sha256:53a18d21594fb60606841ceb279779e7d9f48ee9f08d114e45e9dbc7eed39bcf
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
